### ISSUE TITLE
<commandlineArgs> Not seperating arguments by whitespace

### ISSUE THREAD

**Issue by emmanuel-lopez** [openjfx/javafx-maven-plugin#102]
Just want to say thank you for all your hard work on this project and JavaFx in general.

Using version: 0.0.4
With: `<commandlineArgs>--ip=192.168.1.254 --port=9999 --delay=10000</commandlineArgs>`
According to the commandlineArgs description it should split the string on whitespace and send the values to main.

I tested using the code

```
public class App extends Application {

    public static void main(String[] args) {        
        launch(args);        
    }

    @Override
    public void start(Stage stage) {        
	System.out.println(getParameters().getRaw());
        System.out.println(getParameters().getNamed().get("ip"));
	...
    }
}
```

It prints:
```
[--ip=192.168.1.254 --port=9999 --delay=10000]
192.168.1.254 --port=9999 --delay=10000
```  

The correct output should be:
```
[--ip=192.168.1.254, --port=9999, --delay=10000]
192.168.1.254
```

But the plugin is not splitting the commandlineArgs by whitespace and instead doing something like sending new String[]{commandlineArgs-value} to main();

**Comment by betanzos** [comment]
Similar issue was reported in #75 for `options`, so I will fixed with the same approach.
