### ISSUE TITLE
JavaFX implements

### ISSUE THREAD

**Issue by logindaten** [openjfx/javafx-maven-plugin#114]
Hello everybody
I desperately need your help...
The day before yesterday I wanted to set up my first JavaFX project and proceeded according to the installation descriptions
Create a private library with JavaFX and save the Java FX16 lib:
C: \ Program Files \ Java \ javafx-sdk-16 \ lib
Download javafx in eclipse
Create bibliotek in the javaFX project
Run configuration store the file path
--module-path "C: \ Program Files \ Java \ javafx-sdk-16 \ lib" --add-modules javafx.controls, javafx.fxml

now comes the following error:
error: Could not create the java virtual machine
error: a fatal exception has occurred. program wants exit
Unrecognized option: --module-path

I tried the installation x times but without success

**Comment by logindaten** [comment]
![1](https://user-images.githubusercontent.com/77147412/110598089-a7bedd80-8181-11eb-8a57-d8306301da9b.PNG)
![2](https://user-images.githubusercontent.com/77147412/110598105-ab526480-8181-11eb-8db5-4bd8c59cddf0.PNG)
![3](https://user-images.githubusercontent.com/77147412/110598113-ad1c2800-8181-11eb-869d-e052a9c998e1.PNG)

**Comment by betanzos** [comment]
You must to use a JDK 9 or higher un order to use the modulepath in a Java aplication. 

Nevertheless, [it is required to have a recent version of JDK 15, or at least JDK 11.](https://openjfx.io/openjfx-docs/)

**Comment by logindaten** [comment]
I also tried JDK15 ...
the same error always appears with this version as well

**Comment by logindaten** [comment]
@betanzos 
I also tried JDK15 ...
the same error always appears with this version as well
![1](https://user-images.githubusercontent.com/77147412/110658797-4a974c00-81c2-11eb-9cd0-514899a6ee60.PNG)

**Comment by logindaten** [comment]
![2](https://user-images.githubusercontent.com/77147412/110664086-67824e00-81c7-11eb-9b25-07b351a2b76a.PNG)
No JREs in workspace compatible with specified execution environment j

**Comment by betanzos** [comment]
This issue is not related with this plugin. You must research how to configure Eclipse un the right way for develop JavaFX apps.
