### ISSUE TITLE
info: Toolchain in javafx-maven-plugin null

### ISSUE THREAD

**Issue by jperedadnr** [openjfx/javafx-maven-plugin#129]
PR #118 adds toolchain support, and introduces an info logging that will be `Toolchain in javafx-maven-plugin null` in most of the cases, which can be confusing for the developer.
This should be moved to debug, or kept as info only if the toolchain is not null

**Comment by jperedadnr** [comment]
@tbee can you look into this?

**Comment by tbee** [comment]
Sure.

**Comment by tbee** [comment]
https://github.com/openjfx/javafx-maven-plugin/pull/130

**Comment by abhinayagarwal** [comment]
Fixed by #130
