### ISSUE TITLE
On OSX, how to set the name on the Menu Bar

### ISSUE THREAD

**Issue by zcaudate** [openjfx/javafx-maven-plugin#16]
Is there a way to set this: https://stackoverflow.com/questions/18857837/change-the-application-name-at-runtime-on-mac-for-a-javafx-based-app with the plugin?

**Comment by jperedadnr** [comment]
That can be actually done running the `jpackage` tool, which is not released yet. See http://jdk.java.net/jpackage/

So far, the `javafx-maven-plugin` includes goals to run the app (`javafx:run`) and create a runtime image (`javafx:jlink`), but it doesn't include a goal to run `javafx:jpackage` yet.

You can try manually to create the application or the installer running `jpackage` (requires JDK 13) after you run `javafx:jlink` (using JDK 11 or 12), something like:

```
jpackage create-app-image -o outputdir -n name\
    -m moduleName/className --runtime-image appRuntimeIMage
```
