### ISSUE TITLE
Path exceptions are excluded from generated classpath

### ISSUE THREAD

**Issue by atdixon** [openjfx/javafx-maven-plugin#18]
I necessarily depend on jar(s) with classes in the default java package. JavaFXBaseMojo uses  `LocationManager.resolvePaths` to calculate the class- and module- paths. However when a jar dependency has classes in the default java package an exception is thrown by the `LocationManager` logic (as it attempts to infer dependency modules) and it records these exceptions in its `result.getPathExceptions()` -- the javafx-maven-plugin then subsequently omits these path exceptions from any of the class- and module- paths it generates for the java execution command-line.

One solution (proposed here: https://github.com/openjfx/javafx-maven-plugin/pull/17) would be to simply always include these path exceptions at the tail of the produced classpath. This seems the simplest approach. However we may wish to make this behavior enabled only by a configuration option, something such as `includePathExceptionsInClasspath`.

A broader solution would be to introduce configuration that allows users to exclude/include specific dependencies on the classpath or modulepath so as to override the inference done by the javafx-maven-plugin, though this would require a bit more work. (The maven-shade-plugin or maven-exec-plugin have examples/precedent for specifying artifact inclusions/exclusions type configuration for plugin configs.)

**Comment by atdixon** [comment]
Here is a very simple demo of this issue:

https://github.com/atdixon/demo-ywglmcxj/tree/master

**Comment by jperedadnr** [comment]
Ok, thanks for the sample, that clarifies the issue a little bit more.

If I get it right, `getPathExceptions` returns the files that couldn't be processed, but for now it just only logs the warning. 

With your proposal we'll try to tail them to the class path, no matter what the exception was, which looks quite dangerous to me. 

Even if the cause is well defined, like in your case, where the message shows it is related to `unnamed package not allowed`, do you think in all the cases it is safe to keep those jars in the classpath?

At the very least, I'd say we add a boolean property like you have proposed (`includePathExceptionsInClasspath`), that will be false by default.

**Comment by atdixon** [comment]
> If I get it right, getPathExceptions returns the files that couldn't be processed, but for now it just only logs the warning.

Yes, a warning is logged and the offending file (jar) is not included in any classpath/modulepath.

> Even if the cause is well defined, like in your case, where the message shows it is related to unnamed package not allowed, do you think in all the cases it is safe to keep those jars in the classpath?

This is a good question. My thinking is that if you've declared a jar as a maven dependency, then there should be no harm in putting it in the classpath _even if_ the javafx-maven-plugin had trouble processing it as a JPMS module. After all the user, will still see the warning indicating the issue and they can decide if they need to fix things or not.

If you think of it from the standard Maven side of things... Maven builds up its classpath/s without inspecting/validating the contents of the JARs... so in a standard maven scenario you'll get a classpath and if one of your jars is bad/corrupted you will simply find out at runtime.

That said, I realize the flag `includePathExceptionsInClasspath` would be the safest if not pathological solution. Let me know what you think and I can update the PR with such a flag.

**Comment by jperedadnr** [comment]
At some point you are right, you can put almost _anything_ in the classpath, and nothing should happen.

But I still think we should be here on the safer side adding the flag, and also modifying the warning message: if there is a warning, and the flag is not set, notify the developer that he/she can turn on the flag to bypass it.

Pinging @tiainen here to get a second opinion?

**Comment by atdixon** [comment]
Great idea warning developer so that the flag can be discovered by users encountering issues.

I updated the PR. Let me know what you think. Happy to make any revisions or hand over the patch.
