### ISSUE TITLE
Dependency ignored when it contains default package

### ISSUE THREAD

**Issue by paulmackinlay** [openjfx/javafx-maven-plugin#20]
I have found that if a dependency contains code in the default package, it is not included in the running app. 

Here is an example maven project that shows the problem. It depends on com.fimtra:clearconnect:3.16.0 (which contains code in the default package) 
[jfx-test.zip](https://github.com/openjfx/javafx-maven-plugin/files/3194494/jfx-test.zip)

**Comment by jperedadnr** [comment]
Duplicated from this issue #18. There is already a PR to fix it #17 . Maybe you want to give it a try?

**Comment by paulmackinlay** [comment]
Ah, I should have spotted it was already raised. Anyhow, I have tried the fix and it works - thanks.

**Comment by jperedadnr** [comment]
Thanks for testing.
