### ISSUE TITLE
Fatal Exception when executing javafx:run

### ISSUE THREAD

**Issue by justinhschaaf** [openjfx/javafx-maven-plugin#21]
Hello! I've been attempting to add the JavaFX plugin and dependencies to a project I've been working on; however, whenever I run my program, I am faced with a fatal error that prevents the JVM from starting: 

```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: --module-path
```

The full log is available [here](https://gist.github.com/justinhschaaf/1e6527fd9989a717822595b8edba5c45). I'm using Java 11.0.2 and javafx-maven-plugin 0.0.2.

**Comment by tiainen** [comment]
The error message indicates that the JVM being used is still Java 8, because the `--module-path` option has been introduced with Java 9. Make sure that you configure your maven project to build with Java 11 or later.

**Comment by justinhschaaf** [comment]
It does appear that maven is using Java 8 rather than Java 11; however, my IDE's settings show that maven is using Java 11.

**Comment by jperedadnr** [comment]
As explained here: https://openjfx.io/openjfx-docs/#IDE-Intellij, section Maven projects, if you run from your IDE, the plugin might pick the Java_Home it is using (for instance IntelliJ runs on JDK 1.8), so you can add this to the plugin:
```
<configuration>
    <executable>/path/to/jdk-11/bin/java</executable>
</configuration>
```

Anyway, this shouldn't be necessary, if the project has SDK and language level set to 11, the platform sdk is 11, or if you run from a terminal with Java_Home set to 11.

If any of that works, please detail your IDE and OS versions.

**Comment by justinhschaaf** [comment]
Adding the configuration worked for me. Thank you very much!

**Comment by mkpaz** [comment]
For those who don't want to spoil `pom.xml` with workstation related paths. There are another option. If you're define current JVM version via `JAVA_HOME` env variable, you can just overwrite it in IDE settings.

![изображение](https://user-images.githubusercontent.com/25181998/64590286-41a0a100-d3b8-11e9-8cf3-e0df24c4f5e3.png)

![изображение](https://user-images.githubusercontent.com/25181998/64590465-a0661a80-d3b8-11e9-95fd-2b4867907010.png)

P.S. It's rather confusing that OpenJFX ignores IDE SDK settings and uses JRE from path env variable instead.

**Comment by jperedadnr** [comment]
@mkpaz If you think this can be improved, please file a new issue.
