### ISSUE TITLE
Unrecognized option --module-path with JDK 13

### ISSUE THREAD

**Issue by GabrielBB** [openjfx/javafx-maven-plugin#43]
I've tried all the things said in this post: https://stackoverflow.com/questions/55855335/javafx-and-maven-in-intellij-java-home-set-but-unrecognized-option-module-pa

However, not even using `<executable>` works for me.

**Comment by jperedadnr** [comment]
You are running with Java 1.8, that doesn't recognize modules nor the module-path option.

Make sure you don't have it set in the Windows Path environment variable

**Comment by Bhargav008-jo** [comment]
@jperedadnr , do you mean we shouldn't set the jdk 8 in windows path variable??
