### ISSUE TITLE
After javafx:jlink to run launcher.bat  Unable to load resource file

### ISSUE THREAD

**Issue by XiumingLee** [openjfx/javafx-maven-plugin#45]
First of all，excute `javafx:run`  the application can normal loading of resource files,but after `javafx:jlink` to run launcher.bat , the application Unable to load resource file.

like this `WARNING: Resource "org/kordamp/bootstrapfx/bootstrapfx.css" not found.`

**Comment by GordonGgx** [comment]
I also encountered this problem. How did you solve it
