### ISSUE TITLE
Packaging a multi-platform JavaFX module app.

### ISSUE THREAD

**Issue by MintakaB** [openjfx/javafx-maven-plugin#49]
Hi there
This is not a bug report and the worse escenario would be a feature request.
first of all, excellent work done folks and the things in JavaFX are really getting stream-lined thanks to this project.
There is one feature I don't know how to get through it and it is the packaging of a multiplatform  (win, mac, linux)module app from any of those platforms. This is solved pretty well using a non-modular project and the shade plugin and it works pretty well. However, is there any way to instruct the javafx:jlink task to produce an output, let say for running on windows from a mac machine?.
thank you

**Comment by betanzos** [comment]
Because of `jlink` is platform-dependent you need to run this command on every OS in order to make your platform-specific JRE image.

**Comment by Jiraci** [comment]
Can i compile to linux on windows for example?

**Comment by betanzos** [comment]
> Can i compile to linux on windows for example?

Yes, using WSL.

**Comment by Jiraci** [comment]
Well mac wouldnt be possible then - is there no other way than to download all of the different jdks

**Comment by betanzos** [comment]
Downloading the JDKs for the different platforms is not a problem (look here https://adoptopenjdk.net/releases.html) but what you can't do is use a Linux JDK on Mac / Windows.

Maybe using Docker you can do what you want.

**Comment by MintakaB** [comment]
Still back to this feature. Having a way to pack a multiplatform project would be really nice. Using Java modules seems you always need to run the packaging on the same target OS. Ideally we should be able to distribute one binary to multiple platforms packing multiple JRE at your will. I am not talking of cross-compiling just cop
