### ISSUE TITLE
commandlineArgs are in wrong position

### ISSUE THREAD

**Issue by dukescript** [openjfx/javafx-maven-plugin#51]
If you add commandLineArgs they will not take effect, because they're added at the very end of the call.

**Comment by dukescript** [comment]
according to the readme multiple commandline arguments can be added separated by a whitespace. This also doesn't work the way commandline args are added. See [
53b5681](https://github.com/dukescript/javafx-maven-plugin/commit/53b56817505360c9565bac8203ce0029184b4a90)

**Comment by jperedadnr** [comment]
Not an issue
