### ISSUE TITLE
Got null pointerException when running javafx:jlink

### ISSUE THREAD

**Issue by laurentyj81** [openjfx/javafx-maven-plugin#66]
Hello running mvn javafx:jlink on my project I got the following NullpointerException
Caused by: java.lang.NullPointerException
    at org.openjfx.JavaFXBaseMojo.getExecutablePath (JavaFXBaseMojo.java:368)
    at org.openjfx.JavaFXJLinkMojo.execute (JavaFXJLinkMojo.java:154)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

Any hints on what is going from ?

**Comment by betanzos** [comment]
Please share your POM

**Comment by laurentyj81** [comment]
I have used the simple way to configure openjfx plugin

> 

			<plugin>
				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>0.0.4</version>
				<configuration>
					<mainClass>com.ljo.Jaso.gui.Standalone</mainClass>
				</configuration>
			</plugin>

> 

And also a more sophisticated way, but got exactly the same result
	

> 		<plugin>

				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>0.0.4</version>
				<configuration>
					<mainClass>com.ljo.Jaso.gui.Standalone</mainClass>
					<stripDebug>true</stripDebug>
					<compress>2</compress>
					<noHeaderFiles>true</noHeaderFiles>
					<noManPages>true</noManPages>
					<launcher>JasoUI_openjfx</launcher>
					<jlinkImageName>openjfx</jlinkImageName>
					<jlinkZipName>JasoUI_openjfx_zip</jlinkZipName>
				</configuration>
			</plugin>

>

**Comment by betanzos** [comment]
I can't to reproduce your issue neither in Windows nor in Linux using both configurations

**Comment by betanzos** [comment]
> I can't to reproduce your issue neither in Windows nor in Linux using both configurations

Running the goal from IntelliJ IDEA I got the same problem

**Comment by matthjes** [comment]
I'm running into the same error. Here is the complete POM:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example</groupId>
    <artifactId>protocol-handler</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>14</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>14</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.4</version>
                <configuration>
                    <release>11</release>
                    <jlinkImageName>swhrldm</jlinkImageName>
                    <launcher>launcher</launcher>
                    <executable>C:\Program Files\Java\jdk-14\bin\java.exe</executable>
                    <mainClass>org.example.App</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by betanzos** [comment]
@matthjes from CMD or form an IDE?

I've only had this error once running `javafx:jlink` from IntelliJ and I don't know why, because it never happened to me again.

**Comment by denis-larka** [comment]
Hello, I guess this is due to JAVA_HOME is defined with the brackets like 
JAVA_HOME="C:\...."

**Comment by betanzos** [comment]
> Hello, I guess this is due to JAVA_HOME is defined with the brackets like
> JAVA_HOME="C:...."
> then : javaHomeFromEnv.concat(File.separator).concat("bin") produce unreadable path

If you are talking about this:
`<executable>C:\Program Files\Java\jdk-14\bin\java.exe</executable>`

I did tests with a path like that and work fine.

**Comment by denis-larka** [comment]
Not exactly, if JAVA_HOME env variable defined NPE will rise despite plugin executable tag.
I would suggest sanitizing env by improving getJavaHomeEnv in JavaFXBaseMojo
`
	private String getJavaHomeEnv(Map<String, String> enviro) {
		final String java_home = enviro.get("JAVA_HOME");
		if (java_home != null) {
			String trimmedJavaHome = java_home.replace('\"',' ').replace('\'',' ').trim();
			final Path path = Paths.get(trimmedJavaHome).normalize().toAbsolutePath();
			if(!Files.isDirectory(path)){
				throw new IllegalStateException("JAVA_HOME defined incorrectly:"+path);
			}
			return path.toString();
		}
		return null;
	}
`

**Comment by betanzos** [comment]
> If JAVA_HOME env variable defined with quotes NPE will rise despite plugin executable tag

Double quotes are required if the ENV variable value contain white spaces, because of this when it is loaded by language are removed.

JAVA_HOME definition
![JAVAHOME from CDM](https://user-images.githubusercontent.com/4399580/77859947-801d7200-71c9-11ea-84a2-d8928d7035f9.png)

Plugin configuration
```xml
<plugin>
	<groupId>org.openjfx</groupId>
	<artifactId>javafx-maven-plugin</artifactId>
        <!-- Version for test, same base of code as 0.0.4 -->
	<version>0.0.5-SNAPSHOT</version>
	<configuration>
		<release>11</release>
		<jlinkImageName>swhrldm</jlinkImageName>
		<launcher>launcher</launcher>
		<executable>D:\tools\java\adoptopenjdk 13+33_hotspot\bin\java.exe</executable>
		<mainClass>test.app/com.betanzos.App</mainClass>
	</configuration>
</plugin>
```

Then I have modified the JavaFXBaseMojo.getJavaHomeEnv() method in order to print the value it returns
```java
private String getJavaHomeEnv(Map<String, String> enviro) {
    System.out.println("JavaFXBaseMojo.getJavaHomeEnv(): <" + enviro.get("JAVA_HOME") + ">");
    return enviro.get("JAVA_HOME");
}
```

And this is the `javafx:jlink` output
![output jlink](https://user-images.githubusercontent.com/4399580/77860534-23bc5180-71cd-11ea-8d25-c5187364c672.png)

You may notice that the double quotes are not present, so they are not the cause of the problem.

**Comment by denis-larka** [comment]
C:\Users\denis>set JAVA_HOME="C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot"
C:\Users\denis>echo %JAVA_HOME%
"C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot"

Make sure echo produce an output with double quotes, then "mvn clean install"
Also, I didn't test with an "executable" tag so better to remove it to clean reproduce

**Comment by betanzos** [comment]
Defines JAVA_HOME in this way no requires double quotes for handle withe spaces, so the value is wrong and Maven cannot work with it. 
![Untitled](https://user-images.githubusercontent.com/4399580/77861814-967cfb00-71d4-11ea-82ca-1961aa706241.png)

I think that this type of problem should not be handled by the plugin since it is a problem of bad configuration of the environment variable since this value is not a valid path.

**Comment by denis-larka** [comment]
In my case maven not complaining, only the plugin produces NPE.

**Comment by betanzos** [comment]
> In my case maven not complaining, only the plugin produces NPE.

Can you share the output of the command `mvn --version`?

**Comment by denis-larka** [comment]
Do we have clear instruction somewhere in README that you must do `mvn --version` to validate the environement before using a plugin ?

**Comment by betanzos** [comment]
No, this not about the plugin, that is a useful command to know the configuration of our maven.

**Comment by denis-larka** [comment]
Well, I gave you clear steps to reproduce NPE, if you don't want to fix, up to you, I only sympathize with those who fall for it without any clue.

**Comment by betanzos** [comment]
Yes, but I do not agree to fix a problem related to an wrong configuration of the development environment. So I want to see your `mvn --version` output since you say that maven is going well for you.

Anyway, you are free to open a PR with your proposal of fix.

**Comment by denis-larka** [comment]
`mvn -version` show me that the environment is wrong, but `mvn clean install` with a plugin - don't. 
A plugin is used by people, people can do mistakes, and it is a good practice at least to tell what exactly goes wrong.

**Comment by betanzos** [comment]
As I said, this is an environment configuration problem due to an invalid path and in my case all commands fail. If you disagree with me please make a PR.

![mvn broke](https://user-images.githubusercontent.com/4399580/77863387-38a1e080-71df-11ea-90df-cc491ead4ba9.png)

**Comment by denis-larka** [comment]
Hello, 
here are my cases:

`
set JAVA_HOME="C:\PROGRA~1\AdoptOpenJDK\jdk-14.0.0.36-hotspot dummy"
mvn clean install
`
dummy""=="" was unexpected at this time.


`
set JAVA_HOME="C:\PROGRA~1\AdoptOpenJDK\jdk-14.0.0.36-hotspot"
mvn -version
`
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\denis\data\apache-maven-3.6.3\bin\..
Java version: 14, vendor: AdoptOpenJDK, runtime: C:\PROGRA~1\AdoptOpenJDK\jdk-14.0.0.36-hotspot
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

`
set JAVA_HOME="C:\PROGRA~1\AdoptOpenJDK\jdk-14.0.0.36-hotspot"
mvn clean install
`
[ERROR] Failed to execute goal org.openjfx:javafx-maven-plugin:0.0.4:jlink (default) on project fx-bo-common-blog: Execution default of goal org.openjfx:javafx-maven-plugin:0.0.4:jlink failed.: NullPointerException -> [Help 1]

`
set JAVA_HOME=C:\PROGRA~1\AdoptOpenJDK\jdk-14.0.0.36-hotspot
mvn clean install
`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by betanzos** [comment]
This is a good point:
> set JAVA_HOME="C:\PROGRA~1\AdoptOpenJDK\jdk-14.0.0.36-hotspot"

In this case the plugin should work fine since Maven does. Because of this I'll make a PR fixing it.

**Comment by betanzos** [comment]
Now work fine

![fix](https://user-images.githubusercontent.com/4399580/77954847-832d6680-728c-11ea-81e6-d1ef1de5d7d8.png)
