### ISSUE TITLE
Unable to run profiler

### ISSUE THREAD

**Issue by errael** [openjfx/javafx-maven-plugin#75]
I'm using an IDE, it provide a property, ${vm.args} that I try to use with the javafx-maven-plugin like:
```
    <execution>
        <!-- Configuration for automatic IDE profiling -->
        <id>ide-profile</id>
        <configuration>
            <options>
                <option>${vm.args}</option>
            </options>
            <mainClass>com.raelity.play.xs13.App</mainClass>
        </configuration>
    </execution>
```
Typically vm.args looks like `-XX:+He... -XX:Hea... -agentp...` and it gets treated as a single jvm argument which fails. It needs to be split by whitespace. 

I could be missing the right way to do this. I was wondering about extending the plugin; something like: 
`<optionsString><string>${vm.args}</string></optionsString>`
which would split the string, by default on white space, and add the resulting list to vm options.

BTW, manually taking the value of ${vm.args} and adding them separately as `<option>arg</option>` works and the profiler run OK.

**Comment by betanzos** [comment]
I think it is not necessary to create a new parameter to fix this since the command `javafx:jlink` work fine with options containing spaces. So same behavior we should expect for the `javafx:run` command.

**Comment by errael** [comment]
I thought it might have been that way so that spaces in filenames could be handled.

**Comment by betanzos** [comment]
This topic requires in-depth analysis.

**Comment by errael** [comment]
Yeah. If a string is going to be parsed into arguments, at least simple quoting needs to be taken into account. It can get to be a mess if you let it.

**Comment by errael** [comment]
FYI, here is the string, no CR, that ${vm.args} expands to in my test case
```
 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=F:\tmp\DummyModule\build\testuserdir\var\cache\mavencachedirs\1750554774\org-netbeans-modules-profiler  -agentpath:C:/f/repos/netbeans/nbbuild/netbeans/profiler/lib/deployed/jdk16/windows-amd64/profilerinterface.dll=C:\f\repos\netbeans\nbbuild\netbeans\profiler\lib,5140,10
```
It doesn't have spaces in filenames, but it does seem that will happen. It does have multiple contiguous spaces. I don't know if the IDE is running on multiple systems, there might be more or less args.

**Comment by betanzos** [comment]
This is working for me (see commit [7697b30](https://github.com/openjfx/javafx-maven-plugin/pull/76/commits/7697b30c240e5306767fc114121ce3a725bab2be))

![Untitled](https://user-images.githubusercontent.com/4399580/78417981-40092580-75f5-11ea-8fa6-2edce6ba3ff9.png)

**Comment by errael** [comment]
Looked into NetBeans code to get some test cases, with your 0.0.5-SNAPSHOT, ran these tests. The results look good
```

test1:
    <option>-agentpath:"f1"="f2",1,2</option>
    ...exe, -agentpath:"f1"="f2",1,2, --mo...

test2:
    <option>-agentpath:"f 1"="f 2",1,2</option>
    ...exe, -agentpath:"f 1"="f 2",1,2, --mod...

test3:
    <option> -XX:dumppath="xxx yy" -agentpath:"f 1"="f 2",1,2</option>
    ....exe, -XX:dumppath="xxx yy", -agentpath:"f 1"="f 2",1,2, --mo...
```

**Comment by betanzos** [comment]
Good news, thanks.
