### ISSUE TITLE
`javafx:jlink` doesn't patch launcher file for Windows 

### ISSUE THREAD

**Issue by betanzos** [openjfx/javafx-maven-plugin#78]
Because of this `<options>` and `<commandlineArgs>` configuration parameters values are missing in launcher file `.bat` unlike in bash script.

Plugin configuration
![plugin](https://user-images.githubusercontent.com/4399580/79032990-33924900-7b70-11ea-971d-2f2bdf3ec50e.png)

Generated launcher scripts
![launcher](https://user-images.githubusercontent.com/4399580/79033082-f2e6ff80-7b70-11ea-906b-6a2939dc0461.png)

Related with #77

**Comment by abhinayagarwal** [comment]
Fixed by #79
