### ISSUE TITLE
javafx:compile doesnt exist

### ISSUE THREAD

**Issue by mortensen** [openjfx/javafx-maven-plugin#81]
Your documentation:
"mvn javafx:compile"

Console output:
Could not find goal 'compile' in plugin org.openjfx:javafx-maven-plugin:0.0.4 among available goals jlink, run -> [Help 1]

**Comment by JTMMartins** [comment]
same problem.

**Comment by mortensen** [comment]
I solved this by using blink. But I guess if you aren't yet using jigsaw module system you need compile?

**Comment by betanzos** [comment]
> mvn javafx:compile

Use `mvn compile` instead. The command `javafx:compile` was removed but documentation is outdated.

`mvn clean javafx:jlink` work fine.

**Comment by tiainen** [comment]
Yes, thanks for pointing this out. We'll update the docs to reflect the latest changes.

**Comment by odbuser2** [comment]
Tripped me up to...

**Comment by dwhitla** [comment]
> > mvn javafx:compile
> 
> Use `mvn compile` instead. The command `javafx:compile` was removed but documentation is outdated.
> 
> `mvn clean javafx:jlink` work fine.

This is broken too. 

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/18676080/82171242-14729e00-990a-11ea-9f01-b03d357a196e.png">

**Comment by betanzos** [comment]
Right, above I put it well

> Use **`mvn compile`** instead.

and below I did not.

This is the right command
```
mvn clean compile javafx:jlink
```

Next version fix this behavior, so `compile` command may be omitted

**Comment by dwhitla** [comment]
This doesn't work either. JavaFXJLinkMojo.jlinkExecutable is not resolved against the current JRE. This results in errors like the following unless to hard code the path to jlink in your POM.

Caused by: java.io.IOException: Cannot run program "jlink" (in directory "/Users/dwhitla/dev/code/samples/java/HelloJFX"): error=2, No such file or directory

**Comment by betanzos** [comment]
I suggest you open another issue since this problem is not related (at first glance) with the project compilation.

**Comment by dwhitla** [comment]
Yes. I think it is related to https://github.com/openjfx/javafx-maven-plugin/issues/50# as it has the same root cause.

**Comment by betanzos** [comment]
> Yes. I think it is related to #50 as it has the same root cause.

It may be so. In any case, please share any configuration that you think is relevant.

> But that issue isn't getting any love it seems.

I think so too. I am waiting for an answer to the question I asked about the desired behavior to try to fix it.

**Comment by dwhitla** [comment]
> > Yes. I think it is related to #50 as it has the same root cause.
> 
> It may be so. In any case, please share any configuration that you think is relevant.
>
For the simplest possible intro I created an empty JavaFX project from the javafx-archetype-simple maven archetype. I would expect following the tutorial verbatim to just work.

> > But that issue isn't getting any love it seems.
> 
> I think so too. I am waiting for an answer to the question I asked about the desired behavior to try to fix it.
Is there enough info in my last comment on that issue? If not I could look at fixing it myself.

**Comment by liugangnhm** [comment]
> Right, above I put it well
> 
> > Use **`mvn compile`** instead.
> 
> and below I did not.
> 
> This is the right command
> 
> ```
> mvn clean compile javafx:jlink
> ```
> 
> Next version fix this behavior, so `compile` command may be omitted

this works for me!
