### ISSUE TITLE
Can't Use with a Non-Modular Proejct When Using Java 11

### ISSUE THREAD

**Issue by cmhulbert** [openjfx/javafx-maven-plugin#88]
The documentation indicates that the plugin can be used for modular or non-modular projects; However, my understanding is that the plugin determines if the project is modular or not based on the java version. This means that java versions which support modularity cannot be run as a non-modular project.

My use case is that I have a java 11 project, NOT taking advantage of the modularity aspect of java 11. I'd rather not convert, as many of the dependencies are not setup to provide modules, and this makes the build unreliable, as you need to rely on the automatic module naming or pathing.

Ideally, I'd like to be able to specify wether my project is modular or not, regardless of the java version

**Comment by betanzos** [comment]
Related with #72 and #73

**Comment by cmhulbert** [comment]
I just tried installing the build at #72 and using that. It didn't work, with the error
```
Error: JavaFX runtime components are missing, and are required to run this
application
```

**Comment by christianitus03** [comment]
Having this exact same problem.

**Comment by betanzos** [comment]
Since version 0.0.5 you can place all dependencies either on `modulepath` or on `classpath`.

For details see `runtimePathOption` option under "[javafx:run options](https://github.com/openjfx/javafx-maven-plugin#javafxrun-options)" section of `README.md`.

**Comment by abhinayagarwal** [comment]
Closing as Not An Issue.
