### ISSUE TITLE
Making jar file

### ISSUE THREAD

**Issue by kingGarfield** [openjfx/javafx-maven-plugin#9]
Hi
Can u provide a guide in main page for creating executable jar file?
I have tried to package my application in a jar file but i get this error when opening jar file in windows.
Error: JavaFX runtime components are missing, and are required to run this application

**Comment by jperedadnr** [comment]
The goals of this plugin are so far `compile` and `run`, so it is a JavaFX dedicated version of the `exec` plugin, intended to run your project with mvn.

Of course, it could be extended to provide other goals like `jlink` or even `jpackage`, as these will be the preferred ways of distribution.

For packaging your project in an executable jar, see 
https://openjfx.io/openjfx-docs/#modular, last section about creating fat jars.
